In [2]:
import pandas as pd

# Replace 'your_file.csv' with the exact file name and extension
file_path = '/content/drive/MyDrive/final project sample data/10000 Movies Data'
data = pd.read_csv(file_path)

In [3]:
data.head()

,Unnamed: 0,Movie_id,title,Genres,release_date,Keywords,overview,poster_path,Budget,Revenue,popularity,vote_average,vote_count
0,0,238,The Godfather,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",1972-03-14,"[{'id': 131, 'name': 'italy'}, {'id': 697, 'na...","Spanning the years 1945 to 1955, a chronicle o...",/3bhkrj58Vtu7enYsRolD1fZdja1.jpg,245066411,245066411,93.552,8.7,16814
1,1,278,The Shawshank Redemption,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",1994-09-23,"[{'id': 378, 'name': 'prison'}, {'id': 417, 'n...",Framed in the 1940s for the double murder of h...,/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg,28341469,28341469,78.664,8.7,22542
2,2,240,The Godfather Part II,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",1974-12-20,"[{'id': 131, 'name': 'italy'}, {'id': 700, 'na...",In the continuing saga of the Corleone crime f...,/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg,102600000,102600000,55.752,8.6,10187
3,3,19404,Dilwale Dulhania Le Jayenge,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",1995-10-19,[],"Raj is a rich, carefree, happy-go-lucky second...",/2CAL2433ZeIihfX1Hb2139CX0pW.jpg,100000000,100000000,22.150,8.6,3927
4,4,424,Schindler's List,"[{'id': 18, 'name': 'Drama'}, {'id': 36, 'name...",1993-12-15,"[{'id': 818, 'name': 'based on novel or book'}...",The true story of how businessman Oskar Schind...,/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg,321365567,321365567,53.542,8.6,13382

In [4]:
# Assuming 'column_name' is the name of your column
unique_values = data['Genres'].unique()

# To display the unique values
print(unique_values)

["[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name': 'Crime'}]"
 "[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'name': 'Drama'}, {'id': 10749, 'name': 'Romance'}]"
 "[{'id': 18, 'name': 'Drama'}, {'id': 36, 'name': 'History'}, {'id': 10752, 'name': 'War'}]"
 ...
 "[{'id': 27, 'name': 'Horror'}, {'id': 53, 'name': 'Thriller'}, {'id': 80, 'name': 'Crime'}, {'id': 9648, 'name': 'Mystery'}]"
 "[{'id': 28, 'name': 'Action'}, {'id': 35, 'name': 'Comedy'}, {'id': 18, 'name': 'Drama'}, {'id': 37, 'name': 'Western'}]"
 "[{'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}, {'id': 10770, 'name': 'TV Movie'}]"]

In [5]:
from ast import literal_eval
from pandas import json_normalize

In [6]:
# Convert string representations to actual lists
data['Genres'] = data['Genres'].apply(literal_eval)

# Explode 'Genres' into separate rows
exploded_genres = data.explode('Genres')

# Normalize the dictionaries in each row to separate columns
normalized_genres = json_normalize(exploded_genres['Genres'])

# Display the result
print(normalized_genres)

            id      name
0         18.0     Drama
1         80.0     Crime
2         18.0     Drama
3         80.0     Crime
4         18.0     Drama
...        ...       ...
25732     35.0    Comedy
25733  10751.0    Family
25734  10770.0  TV Movie
25735     28.0    Action
25736     27.0    Horror

[25737 rows x 2 columns]

In [7]:
# Assuming 'name' is the column with genre names in normalized_genres
genre_counts = normalized_genres['name'].value_counts()

# Display the genre counts
print(genre_counts)

Drama              4635
Comedy             3661
Thriller           2645
Action             2210
Romance            1705
Adventure          1543
Crime              1477
Horror             1342
Family             1147
Science Fiction    1099
Fantasy            1089
Animation           912
Mystery             886
History             485
War                 327
Music               288
Western             145
TV Movie            139
Name: name, dtype: int64